### ISSUE TITLE
[Bug]: Problem with batch replace specific characters

### ISSUE THREAD

**Issue by Heart1010** [rxliuli/joplin-utils#104]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-batch-web

### Describe the bug

I'm using your new **Joplin Batch v0.2.1** plugin and trying to replace hundred of notes which include the following text e.g.
`Bestellbestätigung<br>Bestellung #[028-0332872-4531555](https://www.amazon.de/gp/f.html?C=3ILR4VQxyz)`

I want to search for `Bestellung #` and replace it with `Bestellung`.

But your plugin can't deal with that `#`, can it?

Because the search results for `Bestellung #` include every note which has the text `Bestellung` in it - it doesn't only find the notes with `Bestellung #` ("space #" after the word "Bestellung").

### Steps to reproduce the behavior

see description above

### log file

not needed

**Comment by rxliuli** [comment]
I simply tested it and found no problem, maybe you can add some screenshots?

<img width="1226" alt="image" src="https://github.com/user-attachments/assets/ff00abed-83e5-4711-b4f4-40c8224abc13">
<img width="1235" alt="image" src="https://github.com/user-attachments/assets/fe1d3168-670b-442f-bde4-b9a68b02cb41">

**Comment by Heart1010** [comment]
strange 🤔 

When I do the exact same every note which has `Bestellung` as text somewhere in a note is found (not only the `Bestellung #` notes). And when I open such a "found note" nothing is shown as a diff (which is correct because there isn't any `Bestellung #` in the note text at all!

See animated gif picture....
![joplin_batch_bug](https://github.com/user-attachments/assets/1b57ea6d-922d-48ac-bf42-c4a6df148934)

_(I censored my private name/adress - there is only "Bestellung" at top as text in it and no "Bestellung #" at all the text of that note)_

**Comment by rxliuli** [comment]
It is indeed the case. Even if it only contains `Bestellung`, it will be searched. It should be a Joplin search problem. But you can rest assured that the replacement will only be modified if it shows the part to be replaced, otherwise it will remain the same (even if it does appear in the search list). But it's a bit confusing, and I'll manually filter it again on the plugin side and publish a new version.

<img width="570" alt="image" src="https://github.com/user-attachments/assets/63e5f13b-bade-4401-92fa-11076eab1cee">

<img width="588" alt="image" src="https://github.com/user-attachments/assets/9097a832-df89-4597-aeb1-aa9d6474a61b">

**Comment by rxliuli** [comment]
> In general - is it possible (or is on the roadmap) to support regex search phrases?

I'm not sure that supporting regular expressions will drastically reduce performance, since Joplin doesn't natively support regular expression searches, meaning I need to loop through all the notes and match them one by one.

**Comment by Heart1010** [comment]
ok
